"""Reading ssh_config Host blocks into hosts, and writing hosts back out."""

import getpass
import re
import shlex
from dataclasses import dataclass, field

from .models import Host, Inventory, check_port

_KEYWORD = re.compile(r"^(\w+)\s*(?:=\s*|\s+)(.*)$")
_PATTERN_CHARS = set("*?!")


@dataclass
class Block:
    tokens: list[str]
    line: int
    options: list[tuple[str, str]] = field(default_factory=list)


def _split(value: str) -> list[str] | None:
    try:
        return shlex.split(value)
    except ValueError:
        return None


def _single(value: str) -> str:
    """A one-argument value with ssh-style quoting removed."""
    parts = _split(value)
    return parts[0] if parts and len(parts) == 1 else value


def _quote(value: str) -> str:
    if value and not any(c.isspace() or c in "\"'" for c in value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse(text: str, source: str) -> tuple[list[Block], list[str]]:
    """Host blocks that name concrete hosts, plus warnings for everything skipped."""
    blocks: list[Block] = []
    warnings: list[str] = []
    current: Block | None = None
    skipping = False

    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = _KEYWORD.match(line)
        if not match:
            warnings.append(f"{source}:{n}: can't read {line!r}, skipped")
            continue
        keyword, value = match.group(1), match.group(2).strip()
        lowered = keyword.lower()

        if lowered == "host":
            tokens = _split(value)
            if not tokens:
                warnings.append(f"{source}:{n}: unreadable Host line, block skipped")
                current, skipping = None, True
            elif any(set(t) & _PATTERN_CHARS for t in tokens):
                warnings.append(f"{source}:{n}: Host {value} is a pattern, not a host; block skipped")
                current, skipping = None, True
            else:
                current, skipping = Block(tokens, n), False
                blocks.append(current)
        elif lowered == "match":
            warnings.append(f"{source}:{n}: Match blocks can't be imported; block skipped")
            current, skipping = None, True
        elif lowered == "include":
            warnings.append(f"{source}:{n}: Include not followed; import that file on its own")
        elif skipping:
            continue
        elif current is None:
            warnings.append(f"{source}:{n}: {keyword} outside any Host block, skipped")
        else:
            current.options.append((keyword, value))

    return blocks, warnings


def to_host(block: Block, source: str, warnings: list[str]) -> Host | None:
    """One block as a host. ssh takes the first value of a repeated keyword, so this does too."""
    name, *aliases = block.tokens
    host = Host(name=name, hostname=name, aliases=aliases)
    where = f"{source}:{block.line} ({name})"
    seen: set[str] = set()
    identities_only: tuple[str, str] | None = None

    for keyword, value in block.options:
        lowered = keyword.lower()
        if lowered in seen:
            warnings.append(f"{where}: second {keyword} ignored, ssh uses the first")
            continue
        seen.add(lowered)
        match lowered:
            case "hostname":
                host.hostname = _single(value)
            case "user":
                host.user = _single(value)
            case "port":
                try:
                    host.port = check_port(int(_single(value)), where)
                except ValueError:
                    warnings.append(f"{where}: Port {value!r} is not a number; host skipped")
                    return None
            case "identityfile":
                host.ssh_key = _single(value)
            case "identitiesonly":
                identities_only = (keyword, value)
            case _:
                host.ssh_options[keyword] = value

    # Export writes "IdentitiesOnly yes" next to every key. Keep anything that would resolve differently.
    if identities_only and not (host.ssh_key and identities_only[1].lower() == "yes"):
        host.ssh_options[identities_only[0]] = identities_only[1]
    elif host.ssh_key and not identities_only:
        host.ssh_options["IdentitiesOnly"] = "no"

    # Pin what ssh would have used, so inventory defaults can't change how this host resolves.
    host.user = host.user or getpass.getuser()
    host.port = host.port or 22
    return host


def render(inventory: Inventory) -> str:
    lines = [f"# Generated by hosts-inventory from {inventory.path.name}. Do not edit.", ""]
    for host in sorted(inventory.hosts, key=lambda h: h.name.casefold()):
        for note in host.notes.splitlines():
            lines.append(f"# {note}".rstrip())
        lines.append("Host " + " ".join(_quote(t) for t in host.tokens()))
        lines.append(f"    HostName {_quote(host.hostname)}")
        lines.append(f"    User {_quote(inventory.user(host))}")
        port = inventory.port(host)
        if port != 22:
            lines.append(f"    Port {port}")
        options = inventory.ssh_options(host)
        key = inventory.ssh_key(host)
        if key:
            lines.append(f"    IdentityFile {_quote(key)}")
            if not any(k.lower() == "identitiesonly" for k in options):
                lines.append("    IdentitiesOnly yes")
        for keyword, value in options.items():
            lines.append(f"    {keyword} {value}")
        lines.append("")
    return "\n".join(lines)
