"""The table module: Markdown or CSV per output, the bytes ls --format prints for the same columns,
written through export and the guard like any other module's files."""

import ast
import hashlib
import json
import stat
from pathlib import Path

import pytest

from conftest import MIXED, write_config, write_listed
import ari
from ari import core
from ari.cli import main
from ari.config import load_config
from ari.errors import HostsError

TABLES = MIXED + """
[[inventories.personal.table.outputs]]
path = "SSH/docs/personal.txt"
format = "csv"
columns = ["name", "os"]
mode = "0600"

[[inventories.work.table.outputs]]
path = "SSH/docs/work.md"
columns = ["name", "hostname", "user", "keys", "os", "groups", "notes"]

[[inventories.work.table.outputs]]
path = "SSH/docs/work.csv"
columns = ["notes", "name", "port"]
"""

HEADER = "<!-- Generated by ari from work.json. Do not edit. -->\n\n"


def run(*argv):
    return main(list(argv))


@pytest.fixture
def tables(home):
    write_listed(home, TABLES)
    return home


def docs(home) -> dict[str, bytes]:
    return {p.name: p.read_bytes() for p in sorted((home / "ssh" / "docs").iterdir())}


def picture(home) -> dict[str, tuple[str, int]]:
    """Every generated file: its hash and mode."""
    return {
        str(p.relative_to(home)): (hashlib.sha256(p.read_bytes()).hexdigest(), stat.S_IMODE(p.stat().st_mode))
        for p in sorted((home / "ssh").rglob("*"))
        if p.is_file()
    }


def ls(capsys, *argv) -> str:
    capsys.readouterr()
    assert run("ls", *argv) == 0
    return capsys.readouterr().out


def test_each_output_is_what_ls_prints_for_its_columns(tables, capsys):
    assert run("export") == 0
    written = docs(tables)
    assert set(written) == {"personal.txt", "work.md", "work.csv"}
    md = ls(capsys, "-i", "work", "--format", "md", "--columns", "name,hostname,user,keys,os,groups,notes")
    assert written["work.md"].decode() == HEADER + md
    assert written["work.csv"].decode() == ls(capsys, "-i", "work", "--format", "csv", "--columns", "notes,name,port")
    assert written["personal.txt"].decode() == ls(capsys, "-i", "personal", "--format", "csv", "--columns", "name,os")
    assert written["personal.txt"] == b"name,os\nnas,TrueNAS 25.04\npi,Raspberry Pi OS 12\nscratch,\n"


def test_export_reports_each_table_and_a_second_export_changes_nothing(tables, capsys):
    assert run("export") == 0
    out = capsys.readouterr().out
    assert f"wrote {tables}/ssh/docs/work.md (work, table, 3 hosts)" in out
    assert f"wrote {tables}/ssh/docs/personal.txt (personal, table, 3 hosts)" in out
    before = picture(tables)
    assert run("export") == 0
    out = capsys.readouterr().out
    assert "wrote" not in out and out.count("unchanged") == len(before) == 8
    assert picture(tables) == before


def test_each_output_takes_its_own_mode(tables, capsys):
    assert run("export") == 0
    modes = {name: mode for name, (_, mode) in picture(tables).items() if "/docs/" in name}
    assert modes == {"ssh/docs/personal.txt": 0o600, "ssh/docs/work.csv": 0o644, "ssh/docs/work.md": 0o644}
    (tables / "ssh" / "docs" / "work.md").chmod(0o640)
    capsys.readouterr()
    assert run("export") == 0
    assert f"unchanged {tables}/ssh/docs/work.md (work, table, 3 hosts); mode set to 0644" in capsys.readouterr().out
    assert stat.S_IMODE((tables / "ssh" / "docs" / "work.md").stat().st_mode) == 0o644


def test_a_host_excluding_the_module_stays_out_of_every_table(tables, capsys):
    assert run("edit", "vault-01", "--exclude", "table") == 0
    assert run("export") == 0
    written = docs(tables)
    assert b"vault-01" not in written["work.md"] and b"vault-01" not in written["work.csv"]
    assert b"web-01" in written["work.md"]
    rows = {line.split()[0]: line.split() for line in ls(capsys, "--columns", "name,table").splitlines()[3:9]}
    assert rows["vault-01"][1] == "excluded" and rows["web-01"][1] == "✓"


def test_the_guard_refuses_a_hand_edit_until_forced(tables, capsys):
    assert run("export") == 0
    target = tables / "ssh" / "docs" / "work.md"
    target.write_text(target.read_text() + "a line by hand\n")
    edited = picture(tables)
    assert run("export") == 1
    assert "work.md: edited since the last export" in capsys.readouterr().err
    assert picture(tables) == edited
    assert run("export", "--force") == 0
    assert "a line by hand" not in target.read_text()


def test_re_importing_the_other_files_leaves_the_tables_as_they_were(tables, capsys):
    assert run("export") == 0
    before = picture(tables)
    assert run("import", "ssh", str(tables / "ssh" / "10-personal.conf"), "-i", "personal") == 0
    assert run("import", "ssh", str(tables / "ssh" / "20-work.conf"), "-i", "work") == 0
    assert run("import", "ansible", str(tables / "ssh" / "ansible"), "-i", "work") == 0
    capsys.readouterr()
    assert run("export") == 0
    assert "wrote" not in capsys.readouterr().out
    assert picture(tables) == before


def test_a_change_to_the_record_shows_in_the_tables_only_where_a_column_holds_it(tables, capsys):
    assert run("export") == 0
    before = docs(tables)
    assert run("edit", "web-01", "--os", "Debian 13") == 0
    capsys.readouterr()
    assert run("export") == 0
    said = {line.split()[1].rsplit("/", 1)[-1]: line.split()[0] for line in capsys.readouterr().out.splitlines()}
    assert said["work.md"] == "wrote" and said["work.csv"] == said["personal.txt"] == said["20-work.conf"] == "unchanged"
    after = docs(tables)
    assert after["work.csv"] == before["work.csv"] and after["personal.txt"] == before["personal.txt"]
    assert b"| web-01 | 192.0.2.10 | admin | lab | Debian 13 | zone_app | front door |" in after["work.md"]


def test_ls_has_a_table_column_once_an_inventory_turns_it_on(tables, capsys):
    assert core.export_modules(load_config()) == ["ssh", "table", "ansible"]
    assert ls(capsys, "--format", "csv").splitlines()[0] == "name,hostname,user,port,ssh,table,ansible,groups,inv"


def test_a_parked_table_writes_nothing_and_has_no_column(home, capsys):
    parked = TABLES
    for name in ("personal", "work"):
        head = f"[[inventories.{name}.table.outputs]]"
        parked = parked.replace(head, f"[inventories.{name}.table]\nenabled = false\n\n{head}", 1)
    write_listed(home, parked)
    assert run("export") == 0
    assert not (home / "ssh" / "docs").exists()
    assert "table" not in core.export_modules(load_config())


def test_it_doesnt_import(tables, capsys):
    assert run("import", "table", str(tables / "ssh" / "docs" / "work.md"), "-i", "work") == 1
    assert "the table module can't import" in capsys.readouterr().err


def test_a_table_sharing_a_path_with_another_target_writes_nothing(home, capsys):
    write_listed(home, MIXED + '\n[[inventories.personal.table.outputs]]\npath = "SSH/20-work.conf"\nformat = "md"\ncolumns = ["name"]\n')
    assert run("export") == 1
    assert "more than one target writes" in capsys.readouterr().err
    assert sorted(p.name for p in (home / "ssh").iterdir()) == []


def config_with(home, outputs: str) -> None:
    write_config(home, MIXED + outputs)


ERRORS = [
    ("[inventories.work.table]\n", "inventories.work.table: needs at least one output:\n\n[[inventories.work.table.outputs]]\n"),
    ("[inventories.work.table]\noutputs = []\n", "needs at least one output"),
    ("[inventories.work.table]\noutputs = \"x\"\n", "needs at least one output"),
    ("[inventories.work.table]\nfile = \"x\"\noutputs = []\n", "inventories.work.table: unknown keys ['file']"),
    ("[inventories.work.table]\noutputs = [\"x\"]\n", "inventories.work.table.outputs[0]: expected a table with path and columns"),
    ('[[inventories.work.table.outputs]]\ncolumns = ["name"]\n', 'outputs[0]: needs path = "~/path/to/hosts.md"'),
    ('[[inventories.work.table.outputs]]\npath = "docs/hosts.md"\ncolumns = ["name"]\n', "outputs[0].path: use an absolute path or one starting with ~"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.txt"\ncolumns = ["name"]\n', 'outputs[0]: hosts.txt ends in neither .md nor .csv, so it needs format = "md" or "csv"'),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\nformat = "html"\ncolumns = ["name"]\n', 'outputs[0].format: use "md" or "csv"'),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\n', "outputs[0]: needs columns = [\"name\", \"hostname\", ...]: name, hostname, aliases"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = []\n', "outputs[0]: needs columns"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = "name"\n', "outputs[0]: needs columns"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name", "nope"]\n', "outputs[0].columns: no column 'nope'; there are name, hostname"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name", "ssh"]\n', "outputs[0].columns: 'ssh' is ls's column for what export writes, not part of the record"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["os", "name", "os"]\n', "outputs[0].columns: 'os' is named twice"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nmode = 0o644\n', "outputs[0].mode: an octal string you can read and write"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nmode = "0444"\n', "outputs[0].mode"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nmode = "0688"\n', "outputs[0].mode"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nmode = "rw-r--r--"\n', "outputs[0].mode"),
    ('[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nsort = "name"\n', "outputs[0]: unknown keys ['sort']"),
    ('[[inventories.work.table.outputs]]\npath = "~/a.md"\ncolumns = ["name"]\n\n[[inventories.work.table.outputs]]\npath = "~/b"\ncolumns = ["name"]\n',
     "inventories.work.table.outputs[1]: b ends in neither"),
]


@pytest.mark.parametrize("outputs, message", ERRORS)
def test_settings_a_table_cant_use_stop_every_command(home, capsys, outputs, message):
    config_with(home, "\n" + outputs)
    with pytest.raises(HostsError) as refused:
        load_config()
    assert message in str(refused.value)
    assert run("export") == 1
    assert message in capsys.readouterr().err
    assert not any((home / "ssh").iterdir())


@pytest.mark.parametrize("mode, octal", [("0600", 0o600), ("644", 0o644), ("0664", 0o664), ("0700", 0o700)])
def test_a_mode_is_an_octal_string(home, mode, octal):
    config_with(home, f'\n[[inventories.work.table.outputs]]\npath = "~/hosts.md"\ncolumns = ["name"]\nmode = "{mode}"\n')
    (table,) = load_config().get("work").modules["table"].settings
    assert table.mode == octal and table.format == "md" and table.columns == ("name",)


def test_a_host_holds_no_table_data(tables, capsys):
    path = tables / "config" / "ari" / "work.json"
    data = json.loads(path.read_text())
    data["hosts"][0]["modules"] = {"table": {"columns": ["name"]}}
    path.write_text(json.dumps(data))
    assert run("ls") == 1
    assert "unknown keys ['columns']" in capsys.readouterr().err


def imported(path: Path) -> set[str]:
    """The ari modules a source file imports, as dotted names relative to the package."""
    names = set()
    for node in ast.walk(ast.parse(path.read_text())):
        if isinstance(node, ast.ImportFrom):
            base = ("." * node.level) + (node.module or "")
            names |= {base} | {f"{base}.{a.name}" if node.module else f"{base}{a.name}" for a in node.names}
        elif isinstance(node, ast.Import):
            names |= {a.name for a in node.names}
    return names


def test_modules_and_columns_never_import_core():
    """Core finds modules through the registry and reads columns; neither reaches back."""
    package = Path(ari.__file__).parent
    for path in [*sorted((package / "modules").glob("*.py")), package / "columns.py"]:
        found = imported(path)
        assert not {n for n in found if n.rstrip(".").endswith("core") or n == "ari.core"}, path.name
    assert imported(package / "modules" / "table.py") >= {"..columns", "..columns.COLUMNS"}
