"""Schema 3: keys are declared once per inventory and listed by name; ssh options ssh uses every
line of can hold a list. A version 2 file upgrades on read and exports the same bytes."""

import json

import pytest

from conftest import MIXED, write_config, write_mixed
from ari import storage
from ari.config import InventoryConfig
from ari.errors import HostsError
from ari.cli import main
from ari.models import Defaults, Host, Inventory, KeyDef, declare_key, key_name
from ari.modules.ssh import render


def run(*argv):
    return main(list(argv))


def path_of(home, name="personal"):
    return home / "config" / "ari" / f"{name}.json"


def data(home, name="personal"):
    return json.loads(path_of(home, name).read_text())


def stored(home, host, name="personal"):
    return next(h for h in data(home, name)["hosts"] if h["name"] == host)


def load(tmp_path, content):
    path = tmp_path / "personal.json"
    path.write_text(json.dumps(content) if not isinstance(content, str) else content)
    return storage.load(InventoryConfig("personal", path))


# Names


@pytest.mark.parametrize(
    "path, taken, name",
    [
        ("~/.ssh/work-ed25519", [], "work-ed25519"),
        ("~/.ssh/id_rsa", ["id_rsa"], "id_rsa-2"),
        ("~/.ssh/id_rsa", ["id_rsa", "id_rsa-2"], "id_rsa-3"),
        ("~/.ssh/server.pem", [], "server"),
        ("~/.ssh/.hidden", [], "hidden"),
        ("~/keys/my key", [], "my-key"),
        ("~/.ssh/...", [], "key"),
    ],
)
def test_a_key_is_named_after_its_stem(path, taken, name):
    assert key_name(path, taken) == name


def test_declare_key_reuses_the_first_declaration_at_a_path():
    keys = {"a": KeyDef("~/.ssh/a"), "a-old": KeyDef("~/.ssh/a")}
    assert declare_key(keys, "~/.ssh/a") == "a"
    assert declare_key(keys, "~/.ssh/b/a") == "a-2"
    assert keys["a-2"] == KeyDef("~/.ssh/b/a")


# The version 2 upgrade


V2 = {
    "version": 2,
    "defaults": {"user": "deploy", "ssh_key": "~/.ssh/lab-ed25519"},
    "hosts": [
        {"name": "a", "hostname": "192.0.2.1", "ssh_key": "~/.ssh/old/id_rsa"},
        {"name": "b", "hostname": "192.0.2.2", "ssh_key": "~/.ssh/new/id_rsa"},
        {"name": "c", "hostname": "192.0.2.3", "ssh_key": "~/.ssh/old/id_rsa"},
        {"name": "d", "hostname": "192.0.2.4", "ssh_key": ""},
        {"name": "e", "hostname": "192.0.2.5"},
    ],
}


def test_version_2_declares_each_path_once_defaults_first(tmp_path):
    inventory = load(tmp_path, V2)
    assert inventory.keys == {
        "lab-ed25519": KeyDef("~/.ssh/lab-ed25519"),
        "id_rsa": KeyDef("~/.ssh/old/id_rsa"),
        "id_rsa-2": KeyDef("~/.ssh/new/id_rsa"),
    }
    assert inventory.defaults.keys == ["lab-ed25519"]
    assert [h.keys for h in inventory.hosts] == [["id_rsa"], ["id_rsa-2"], ["id_rsa"], [], []]
    assert [inventory.identity_files(h) for h in inventory.hosts][-2:] == [["~/.ssh/lab-ed25519"]] * 2


def test_version_2_saves_as_version_3(tmp_path):
    inventory = load(tmp_path, V2)
    storage.save(inventory)
    saved = json.loads((tmp_path / "personal.json").read_text())
    assert saved["version"] == 3
    assert list(saved)[:5] == ["version", "last_updated", "defaults", "keys", "groups"]
    assert "ssh_key" not in json.dumps(saved)
    assert saved["keys"]["id_rsa-2"] == {"path": "~/.ssh/new/id_rsa"}
    assert storage.load(InventoryConfig("personal", tmp_path / "personal.json")).to_dict() == inventory.to_dict()


@pytest.mark.parametrize(
    "content, message",
    [
        ({"version": 2, "hosts": [{"name": "a", "hostname": "x", "ssh_key": 5}]}, r"hosts\[0\]: 'ssh_key' must be a string"),
        ({"version": 2, "defaults": {"ssh_key": ["~/.ssh/k"]}}, "defaults: 'ssh_key' must be a string"),
        ({"version": 2, "keys": {}}, r"unknown keys \['keys'\]"),
    ],
)
def test_version_2_that_wasnt_valid_stays_refused(tmp_path, content, message):
    with pytest.raises(HostsError, match=message):
        load(tmp_path, content)


def test_upgraded_inventory_exports_the_same_bytes(home):
    """write_mixed is version 2; the expected text is what 0.6.1 wrote for it."""
    write_mixed(home)
    assert run("export") == 0
    assert (home / "ssh" / "20-work.conf").read_text() == (
        "# Generated by ari from work.json. Do not edit.\n\n"
        "Host fw\n    HostName 203.0.113.1\n    User deploy\n    Port 2222\n"
        "    IdentityFile ~/.ssh/lab-ed25519\n    IdentitiesOnly yes\n\n"
        "Host vault-01\n    HostName 192.0.2.30\n    User deploy\n    Port 2222\n"
        "    IdentityFile ~/.ssh/lab-ed25519\n    IdentitiesOnly yes\n\n"
        "Host web-01\n    HostName 192.0.2.10\n    User admin\n"
        "    IdentityFile ~/.ssh/lab-ed25519\n    IdentitiesOnly yes\n"
    )
    hosts = (home / "ssh" / "ansible" / "00-hosts.yml").read_text()
    assert "    ansible_ssh_private_key_file: ~/.ssh/lab-ed25519\n" in hosts
    assert data(home, "work")["version"] == 2  # export reads; only a write converts the file


# Version 3 on its own


@pytest.mark.parametrize(
    "content, message",
    [
        ({"version": 3, "keys": []}, "'keys' must be an object"),
        ({"version": 3, "keys": {"a b": {"path": "~/.ssh/k"}}}, "'a b' can't be a key name"),
        ({"version": 3, "keys": {"~k": {"path": "~/.ssh/k"}}}, "'~k' can't be a key name"),
        ({"version": 3, "keys": {"k": {}}}, "keys.k: missing 'path'"),
        ({"version": 3, "keys": {"k": {"path": ""}}}, "path must be one non-empty line"),
        ({"version": 3, "keys": {"k": {"path": "a\nb"}}}, "path must be one non-empty line"),
        ({"version": 3, "keys": {"k": {"path": "~/.ssh/k", "cert": "x"}}}, r"unknown keys \['cert'\]"),
        ({"version": 3, "hosts": [{"name": "a", "hostname": "x", "keys": "k"}]}, "'keys' must be a list of strings"),
        ({"version": 3, "defaults": {"keys": [1]}}, "'keys' must be a list of strings"),
        ({"version": 3, "hosts": [{"name": "a", "hostname": "x", "ssh_key": "~/.ssh/k"}]}, r"unknown keys \['ssh_key'\]"),
    ],
)
def test_broken_version_3_files_fail_loudly(tmp_path, content, message):
    with pytest.raises(HostsError, match=message):
        load(tmp_path, content)


def test_pub_is_kept_as_written(tmp_path):
    inventory = load(tmp_path, {"version": 3, "keys": {"k": {"path": "~/.ssh/k", "pub": "ssh-ed25519 AAAA k"}}})
    assert inventory.to_dict()["keys"] == {"k": {"path": "~/.ssh/k", "pub": "ssh-ed25519 AAAA k"}}


def test_keys_render_in_order_with_identities_only_once():
    keys = {"a": KeyDef("~/.ssh/a"), "b": KeyDef("~/.ssh/my b")}
    inventory = Inventory("t", __import__("pathlib").Path("t.json"), defaults=Defaults(keys=["a"]), keys=keys)
    hosts = [Host("one", "192.0.2.1", keys=["b", "a"]), Host("two", "192.0.2.2")]
    assert render(inventory, hosts).splitlines()[2:] == [
        "Host one",
        "    HostName 192.0.2.1",
        '    IdentityFile "~/.ssh/my b"',
        "    IdentityFile ~/.ssh/a",
        "    IdentitiesOnly yes",
        "",
        "Host two",
        "    HostName 192.0.2.2",
        "    IdentityFile ~/.ssh/a",
        "    IdentitiesOnly yes",
    ]


# Options that hold a list


def options_file(tmp_path, options):
    return {"version": 3, "hosts": [{"name": "a", "hostname": "192.0.2.1", "modules": {"ssh": {"options": options}}}]}


def test_listable_options_render_one_line_per_value(tmp_path):
    inventory = load(tmp_path, options_file(tmp_path, {
        "LocalForward": ["5432 localhost:5432", "8080 localhost:80"],
        "SendEnv": "LANG",
        "ProxyJump": "jump",
    }))
    assert render(inventory, inventory.hosts).splitlines()[4:] == [
        "    LocalForward 5432 localhost:5432",
        "    LocalForward 8080 localhost:80",
        "    SendEnv LANG",
        "    ProxyJump jump",
    ]


def test_a_list_of_one_is_stored_as_its_string(tmp_path):
    inventory = load(tmp_path, options_file(tmp_path, {"RemoteForward": ["9000 localhost:9000"]}))
    assert inventory.hosts[0].modules == {"ssh": {"options": {"RemoteForward": "9000 localhost:9000"}}}


@pytest.mark.parametrize(
    "options, message",
    [
        ({"ProxyJump": ["a", "b"]}, "option ProxyJump takes one value; ssh reads only the first"),
        ({"LocalForward": []}, "must be a string or a non-empty list of strings"),
        ({"DynamicForward": ["1080", 5]}, "must be a string or a non-empty list of strings"),
        ({"SendEnv": ["LANG", "LC_\n"]}, "option SendEnv must be one line"),
        ({"IdentityFile": "~/.ssh/k"}, "IdentityFile can't be an option; it's the keys field"),
    ],
)
def test_lists_only_where_ssh_uses_every_line(tmp_path, options, message):
    with pytest.raises(HostsError, match=message):
        load(tmp_path, options_file(tmp_path, options))


def test_show_and_search_see_every_value(home, capsys):
    write_config(home, MIXED)
    path_of(home).parent.mkdir(parents=True, exist_ok=True)
    path_of(home).write_text(json.dumps(options_file(None, {"LocalForward": ["5432 localhost:5432", "8080 localhost:80"]})))
    assert run("show", "a") == 0
    out = capsys.readouterr().out
    assert "LocalForward 5432 localhost:5432" in out and "LocalForward 8080 localhost:80" in out
    assert run("ls", "--search", "8080") == 0
    assert "1 host" in capsys.readouterr().out


# --key names a declared key, by name or by its file


@pytest.fixture
def mixed(home):
    write_mixed(home)
    return home


def test_key_takes_a_name_or_a_declared_file(mixed, capsys):
    assert run("key", "other", "--path", "~/.ssh/other", "-i", "work") == 0
    assert run("edit", "web-01", "--key", "~/.ssh/other") == 0
    assert run("add", "web-02", "192.0.2.11", "-i", "work", "--key", "other") == 0
    assert stored(mixed, "web-01", "work")["keys"] == ["other"] == stored(mixed, "web-02", "work")["keys"]
    assert data(mixed, "work")["keys"] == {"lab-ed25519": {"path": "~/.ssh/lab-ed25519"}, "other": {"path": "~/.ssh/other"}}


def test_the_default_key_path_is_stored_as_no_key_of_its_own(mixed):
    assert run("edit", "web-01", "--key", "~/.ssh/lab-ed25519") == 0
    assert "keys" not in stored(mixed, "web-01", "work")


def test_empty_key_goes_back_to_the_default(mixed, capsys):
    run("key", "other", "--path", "~/.ssh/other", "-i", "work")
    run("edit", "web-01", "--key", "other")
    assert run("edit", "web-01", "--key", "") == 0
    assert "keys" not in stored(mixed, "web-01", "work")
    run("show", "web-01")
    assert "lab-ed25519 (~/.ssh/lab-ed25519)  (default)" in capsys.readouterr().out


def test_an_undeclared_key_is_refused_with_the_way_to_declare_it(mixed, capsys):
    before = path_of(mixed, "work").read_bytes()
    assert run("edit", "web-01", "--key", "~/.ssh/new", "--key", "nope") == 1
    err = capsys.readouterr().err
    assert "work (web-01): key '~/.ssh/new' isn't declared; ari key NAME --path PATH -i work declares one" in err
    assert "work (web-01): key 'nope' isn't declared" in err
    assert path_of(mixed, "work").read_bytes() == before


def hand_edit(home, name, change, inventory="work"):
    content = data(home, inventory)
    if content["version"] == 2:
        content = storage.load(InventoryConfig(inventory, path_of(home, inventory))).to_dict()
    change(content)
    path_of(home, inventory).write_text(json.dumps(content))


def test_export_and_edit_refuse_an_undeclared_or_repeated_key(mixed, capsys):
    def change(content):
        content["hosts"][2]["keys"] = ["gone", "lab-ed25519", "lab-ed25519"]
        content["defaults"]["keys"] = ["missing"]

    hand_edit(mixed, "web-01", change)
    assert run("export") == 1
    err = capsys.readouterr().err
    assert "work: defaults: key 'missing' isn't declared" in err
    assert "work (web-01): key 'lab-ed25519' is listed twice" in err
    assert "work (web-01): key 'gone' isn't declared" in err
    assert not (mixed / "ssh" / "20-work.conf").exists()
    assert run("edit", "web-01", "--notes", "x") == 1
    assert "key 'gone' isn't declared" in capsys.readouterr().err


# Import maps the source's key files onto the inventory's keys


def test_import_declares_new_paths_and_names_them(personal, tmp_path, capsys):
    source = tmp_path / "src.conf"
    source.write_text("Host a\n  HostName 192.0.2.1\n  IdentityFile ~/.ssh/a-ed25519\n")
    assert run("import", "ssh", str(source)) == 0
    assert "personal: 1 key declared (a-ed25519)" in capsys.readouterr().out
    assert stored(personal, "a")["keys"] == ["a-ed25519"]


def test_reimport_uses_the_declared_key_and_reports_unchanged(personal, tmp_path, capsys):
    source = tmp_path / "src.conf"
    source.write_text("Host a\n  HostName 192.0.2.1\n  IdentityFile ~/.ssh/k\n  IdentitiesOnly yes\n")
    run("import", "ssh", str(source))
    run("edit", "a", "--key", "~/.ssh/k")
    capsys.readouterr()
    assert run("import", "ssh", str(source)) == 0
    out = capsys.readouterr().out
    assert "1 unchanged (a)" in out and "declared" not in out
    assert list(data(personal)["keys"]) == ["k"]


def test_import_numbers_a_name_taken_by_another_path(personal, tmp_path, capsys):
    first, second = tmp_path / "1.conf", tmp_path / "2.conf"
    first.write_text("Host a\n  HostName 192.0.2.1\n  IdentityFile ~/.ssh/old/id_rsa\n")
    second.write_text("Host b\n  HostName 192.0.2.2\n  IdentityFile ~/.ssh/new/id_rsa\n")
    run("import", "ssh", str(first))
    assert run("import", "ssh", str(second)) == 0
    assert "1 key declared (id_rsa-2)" in capsys.readouterr().out
    assert data(personal)["keys"]["id_rsa-2"] == {"path": "~/.ssh/new/id_rsa"}


def test_a_key_only_a_refused_host_used_isnt_declared(personal, tmp_path, capsys):
    run("add", "a", "192.0.2.1")
    source = tmp_path / "src.conf"
    source.write_text("Host a\n  HostName 192.0.2.99\n  IdentityFile ~/.ssh/k\n")
    assert run("import", "ssh", str(source)) == 1
    assert "declared" not in capsys.readouterr().out
    assert data(personal)["keys"] == {}


def test_import_conflicts_on_a_different_key_file(personal, tmp_path, capsys):
    run("key", "k", "--path", "~/.ssh/k")
    run("add", "a", "192.0.2.1", "--key", "k")
    source = tmp_path / "src.conf"
    source.write_text("Host a\n  HostName 192.0.2.1\n  IdentityFile ~/.ssh/other\n")
    assert run("import", "ssh", str(source)) == 1
    assert "a: IdentityFile ~/.ssh/other differs from ~/.ssh/k; not merged" in capsys.readouterr().err
    assert list(data(personal)["keys"]) == ["k"]


def test_ansible_import_names_the_default_key_first(tmp_path):
    from ari.modules.ansible import AnsibleModule

    (tmp_path / "00-hosts.yml").write_text(
        "all:\n  vars:\n    ansible_ssh_private_key_file: ~/.ssh/b/id\n  hosts:\n"
        "    a:\n      ansible_host: 192.0.2.1\n      ansible_ssh_private_key_file: ~/.ssh/a/id\n"
        "    b:\n      ansible_host: 192.0.2.2\n      ansible_ssh_private_key_file: ~/.ssh/b/id\n"
    )
    result = AnsibleModule().read(str(tmp_path))
    assert result.keys == {"id": KeyDef("~/.ssh/b/id"), "id-2": KeyDef("~/.ssh/a/id")}
    assert result.defaults.keys == ["id"]
    assert [h.keys for h in result.hosts] == [["id-2"], ["id"]]


def test_ansible_reimport_of_its_own_export_is_unchanged(home, capsys):
    write_mixed(home)
    assert run("key", "web", "--path", "~/.ssh/web", "-i", "work") == 0
    assert run("edit", "web-01", "--key", "web") == 0
    run("export")
    capsys.readouterr()
    assert run("-i", "work", "import", "ansible", str(home / "ssh" / "ansible")) == 0
    out = capsys.readouterr().out
    assert "2 unchanged (web-01, vault-01)" in out and "declared" not in out


# ari key


def test_key_lists_every_inventory_with_hosts_counted_through_the_defaults(mixed, capsys, monkeypatch):
    monkeypatch.setenv("COLUMNS", "100")
    run("key", "laptop", "--path", "~/.ssh/laptop", "-i", "personal")
    run("key", "web", "--path", "~/.ssh/web", "-i", "work")
    run("edit", "web-01", "--key", "web", "--key", "lab-ed25519")
    capsys.readouterr()
    assert run("key") == 0
    lines = [line for line in capsys.readouterr().out.splitlines() if line.strip()]
    rows = [line.split() for line in lines[2:-1]]
    assert lines[0].split() == ["KEY", "HOSTS", "PATH", "STATE", "INV"]
    assert rows == [
        ["laptop", "0", "~/.ssh/laptop", "missing", "personal"],
        ["lab-ed25519", "3", "(1", "direct)", "~/.ssh/lab-ed25519", "missing", "work"],
        ["web", "1", "~/.ssh/web", "missing", "work"],
    ]
    assert lines[-1] == "3 keys"
    assert run("key", "-i", "personal") == 0
    assert "lab-ed25519" not in capsys.readouterr().out


def test_key_rows_never_cut_a_path(mixed, capsys, monkeypatch):
    monkeypatch.setenv("COLUMNS", "30")
    run("key", "deep", "--path", "~/.ssh/a/very/long/directory/for/one/key-ed25519", "-i", "work")
    capsys.readouterr()
    run("key")
    assert "~/.ssh/a/very/long/directory/for/one/key-ed25519" in capsys.readouterr().out


def test_key_declares_moves_and_reports_no_change(mixed, capsys):
    assert run("key", "spare", "--path", "~/.ssh/spare", "-i", "work") == 0
    assert run("key", "spare", "--path", "~/.ssh/spare", "-i", "work") == 0
    assert run("key", "lab-ed25519", "--path", "~/.ssh/lab-2026", "-i", "work") == 0
    assert capsys.readouterr().out.splitlines() == [
        "declared spare in work", "no change to spare (work)", "updated lab-ed25519 (work)"
    ]
    run("export")
    assert (mixed / "ssh" / "20-work.conf").read_text().count("IdentityFile ~/.ssh/lab-2026\n") == 3


@pytest.mark.parametrize(
    "argv, message",
    [
        (["key", "a b", "--path", "~/.ssh/k"], "work: 'a b' can't be a key name"),
        (["key", "k", "--path", ""], "work: key 'k': path must be one non-empty line"),
        (["key", "k", "--path", "a\nb"], "path must be one non-empty line"),
        (["key", "copy", "--path", "~/.ssh/lab-ed25519"], "~/.ssh/lab-ed25519 is already the file of key 'lab-ed25519'"),
        (["key", "ghost"], "no key 'ghost' in work; --path PATH declares it"),
        (["key", "lab-ed25519"], "nothing to change; pass --path or --rm"),
        (["key", "--path", "~/.ssh/k"], "--path and --rm need a key NAME"),
        (["key", "ghost", "--rm"], "no key 'ghost' in work"),
        (["key", "lab-ed25519", "--rm", "--path", "x"], "--rm takes no other options"),
    ],
)
def test_key_writes_refuse(mixed, capsys, argv, message):
    before = path_of(mixed, "work").read_bytes()
    assert run(*argv, "-i", "work") == 1
    assert message in capsys.readouterr().err
    assert path_of(mixed, "work").read_bytes() == before


def test_a_key_in_use_cant_be_removed(mixed, capsys):
    run("key", "web", "--path", "~/.ssh/web", "-i", "work")
    run("edit", "web-01", "--key", "web")
    run("edit", "vault-01", "--key", "web", "--key", "lab-ed25519")
    capsys.readouterr()
    assert run("key", "lab-ed25519", "--rm", "-i", "work") == 1
    err = capsys.readouterr().err
    assert "work: key 'lab-ed25519' is in the defaults' keys" in err
    assert "work: key 'lab-ed25519' is still listed by 1 host: vault-01" in err
    assert run("key", "web", "--rm", "-i", "work") == 1
    assert "is still listed by 2 hosts: vault-01, web-01" in capsys.readouterr().err
    run("edit", "vault-01", "--key", "")
    run("edit", "web-01", "--unkey", "web")
    assert run("key", "web", "--rm", "-i", "work") == 0
    assert "web" not in data(mixed, "work")["keys"]


# add and edit


def test_keys_append_in_order_and_unkey_runs_first(mixed, capsys):
    for name in ("a", "b", "c"):
        run("key", name, "--path", f"~/.ssh/{name}", "-i", "work")
    assert run("edit", "web-01", "--key", "b", "--key", "~/.ssh/a") == 0
    assert stored(mixed, "web-01", "work")["keys"] == ["b", "a"]
    assert run("edit", "web-01", "--unkey", "b", "--key", "c", "--key", "b") == 0
    assert stored(mixed, "web-01", "work")["keys"] == ["a", "c", "b"]
    assert run("edit", "web-01", "--key", "", "--key", "c") == 0
    assert stored(mixed, "web-01", "work")["keys"] == ["c"]
    run("export")
    block = (mixed / "ssh" / "20-work.conf").read_text().split("Host web-01\n")[1]
    assert "    IdentityFile ~/.ssh/c\n    IdentitiesOnly yes\n" in block


@pytest.mark.parametrize(
    "argv, message",
    [
        (["edit", "web-01", "--unkey", "lab-ed25519"], "key 'lab-ed25519' comes from the defaults; --key names the keys to use instead"),
        (["edit", "fw", "--unkey", "nope"], "work (fw): doesn't list key 'nope'"),
        (["edit", "web-01", "--key", "lab-ed25519", "--key", "lab-ed25519"], "key 'lab-ed25519' is listed twice"),
    ],
)
def test_key_edits_refuse(mixed, capsys, argv, message):
    before = path_of(mixed, "work").read_bytes()
    assert run(*argv) == 1
    assert message in capsys.readouterr().err
    assert path_of(mixed, "work").read_bytes() == before


def test_show_lists_each_key_with_its_file(mixed, capsys):
    run("key", "id_rsa-2", "--path", "~/.ssh/new/id_rsa", "-i", "work")
    run("edit", "web-01", "--key", "id_rsa-2", "--key", "lab-ed25519")
    capsys.readouterr()
    run("show", "web-01")
    out = "\n".join(line.rstrip() for line in capsys.readouterr().out.splitlines())
    assert "keys       id_rsa-2 (~/.ssh/new/id_rsa)\n           lab-ed25519 (~/.ssh/lab-ed25519)\n" in out
    run("show", "vault-01")
    assert "keys       lab-ed25519 (~/.ssh/lab-ed25519)  (default)" in capsys.readouterr().out
    assert run("ls", "--search", "rsa-2") == 0
    assert "1 host" in capsys.readouterr().out


# --opt: every value for one keyword in one command is its new value


def options_of(home, name):
    return stored(home, name, "work").get("modules", {}).get("ssh", {}).get("options", {})


def test_repeated_opt_sets_a_list_and_one_empty_value_removes_it(mixed):
    assert run("edit", "web-01", "--opt", "LocalForward=5432 localhost:5432", "--opt", "localforward=8080 localhost:80") == 0
    assert options_of(mixed, "web-01") == {"LocalForward": ["5432 localhost:5432", "8080 localhost:80"]}
    assert run("edit", "web-01", "--opt", "LocalForward=9000 localhost:9000") == 0
    assert options_of(mixed, "web-01") == {"LocalForward": "9000 localhost:9000"}
    assert run("edit", "web-01", "--opt", "LocalForward=") == 0
    assert options_of(mixed, "web-01") == {}


@pytest.mark.parametrize(
    "argv, message",
    [
        (["--opt", "ProxyJump=a", "--opt", "ProxyJump=b"], "option ProxyJump takes one value; ssh reads only the first"),
        (["--opt", "SendEnv=LANG", "--opt", "SendEnv="], "ssh option SendEnv is both set and cleared"),
    ],
)
def test_opt_repeats_refused(mixed, capsys, argv, message):
    before = path_of(mixed, "work").read_bytes()
    assert run("edit", "web-01", *argv) == 1
    assert message in capsys.readouterr().err
    assert path_of(mixed, "work").read_bytes() == before
