"""Tables of an inventory's hosts, as Markdown or CSV, each with the columns its output names.
Export only: a table shows the record, and nothing in it is read back."""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..columns import COLUMNS, csv_table, markdown_table
from ..errors import HostsError
from ..models import Host, Inventory
from . import Module, Output, registry

FORMATS = {".md": "md", ".csv": "csv"}
_MODE = re.compile(r"0?[0-7]{3}")


@dataclass(frozen=True)
class Table:
    path: Path
    format: str
    columns: tuple[str, ...]
    mode: int


def _path(value: Any, where: str) -> Path:
    if not isinstance(value, str) or not value:
        raise HostsError(f'{where}: needs path = "~/path/to/hosts.md"')
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise HostsError(f"{where}.path: use an absolute path or one starting with ~")
    return path


def _format(value: Any, path: Path, where: str) -> str:
    if value is None:
        if path.suffix not in FORMATS:
            raise HostsError(f'{where}: {path.name} ends in neither .md nor .csv, so it needs format = "md" or "csv"')
        return FORMATS[path.suffix]
    if value not in FORMATS.values():
        raise HostsError(f'{where}.format: use "md" or "csv"')
    return value


def _columns(value: Any, where: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not value or not all(isinstance(n, str) for n in value):
        raise HostsError(f'{where}: needs columns = ["name", "hostname", ...]: {", ".join(COLUMNS)}')
    for name in value:
        if name not in COLUMNS:
            if name in registry().modules:
                raise HostsError(f"{where}.columns: {name!r} is ls's column for what export writes, not part of the record")
            raise HostsError(f"{where}.columns: no column {name!r}; there are {', '.join(COLUMNS)}")
        if value.count(name) > 1:
            raise HostsError(f"{where}.columns: {name!r} is named twice")
    return tuple(value)


def _mode(value: Any, where: str) -> int:
    if not isinstance(value, str) or not _MODE.fullmatch(value) or int(value, 8) & 0o600 != 0o600:
        raise HostsError(f'{where}.mode: an octal string you can read and write, like "0644" or "0600"')
    return int(value, 8)


def _output(entry: Any, where: str) -> Table:
    if not isinstance(entry, dict):
        raise HostsError(f"{where}: expected a table with path and columns")
    entry = dict(entry)
    path = _path(entry.pop("path", None), where)
    form = _format(entry.pop("format", None), path, where)
    columns = _columns(entry.pop("columns", None), where)
    mode = _mode(entry.pop("mode", "0644"), where)
    if entry:
        raise HostsError(f"{where}: unknown keys {sorted(entry)}")
    return Table(path, form, columns, mode)


def render(inventory: Inventory, hosts: list[Host], table: Table) -> str:
    rows = [(inventory, host) for host in hosts]
    columns = [COLUMNS[name] for name in table.columns]
    if table.format == "csv":
        return csv_table(columns, rows)
    return f"<!-- Generated by ari from {inventory.path.name}. Do not edit. -->\n\n" + markdown_table(columns, rows)


class TableModule(Module):
    name = "table"
    summary = "Markdown or CSV tables of hosts"
    exports = True

    def settings(self, table: dict[str, Any], where: str) -> tuple[Table, ...]:
        table = dict(table)
        outputs = table.pop("outputs", None)
        if table:
            raise HostsError(f"{where}: unknown keys {sorted(table)}")
        key = where.rsplit(": ", 1)[-1]
        if not isinstance(outputs, list) or not outputs:
            raise HostsError(
                f"{where}: needs at least one output:\n\n"
                f'[[{key}.outputs]]\npath = "~/path/to/hosts.md"\ncolumns = ["name", "hostname", "os"]\n'
            )
        return tuple(_output(entry, f"{where}.outputs[{i}]") for i, entry in enumerate(outputs))

    def host_data(self, data: dict[str, Any], where: str) -> dict[str, Any]:
        if data:
            raise HostsError(f"{where}: unknown keys {sorted(data)}")
        return data

    def defaults_data(self, data: dict[str, Any], where: str) -> dict[str, Any]:
        return self.host_data(data, where)

    def describe(self, inventory: Inventory, host: Host) -> list[str]:
        return []

    def export(self, inventory: Inventory, hosts: list[Host], settings: tuple[Table, ...]) -> list[Output]:
        return [Output(t.path, render(inventory, hosts, t).encode("utf-8"), len(hosts), t.mode) for t in settings]
